const menuItems = 
[
    {
        id:1,
        title:'hamburger',
        price:100,
        img:'./img/hamburger.svg'  
    },
    {
        id:2,
        title:'fries',
        price:50,
        img:'./img/fries.svg'
    },
    {
        id:3,
        title:'tea',
        price:10,
        img:'./img/tea.svg'
    },
    {
        id:4,
        title:'cheeseburger',
        price:150,
        img:'./img/hamburger.svg'
    },
    {
        id:5,
        title:'cola',
        price:80,
        img:'./img/cola.svg'
    },
    {
        id:6,
        title:'tea',
        price:20,
        img:'./img/tea.svg'
    }
]
let basketTwo = []
